// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ArkaTrade.Models
{
    [Table("blog")]
    public partial class blog
    {
        [Key]
        public int id { get; set; }
        [StringLength(100)]
        public string title { get; set; }
        [Column(TypeName = "text")]
        public string description { get; set; }
        [Column(TypeName = "date")]
        public DateTime? until { get; set; }
        public byte[] img { get; set; }
        [StringLength(50)]
        public string ContentType { get; set; }
    }
}