// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ArkaTrade.Models
{
    [Table("country")]
    public partial class country
    {
        [Key]
        [StringLength(3)]
        [Unicode(false)]
        public string countrycode { get; set; }
        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string countryname { get; set; }
        [StringLength(2)]
        [Unicode(false)]
        public string code { get; set; }
        public int? show { get; set; }
    }
}