// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ArkaTrade.Models
{
    public partial class Image
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string FileName { get; set; }
        [Required]
        [StringLength(50)]
        public string ContentType { get; set; }
        [Required]
        public byte[] Data { get; set; }
        [StringLength(50)]
        public string dept { get; set; }
    }
}