// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ArkaTrade.Models
{
    public partial class phone
    {
        [Key]
        public int id { get; set; }
        [Column("phone")]
        [StringLength(50)]
        public string phone1 { get; set; }
    }
}